### ISSUE TITLE
Editing in a filtered buggy

### ISSUE THREAD

**Issue by dagnelies** [JonDum/ractive-datatable#2]
Hi,
First of all, this is great! It looks like a promising plugin! :+1:
I noticed that when editing a cell in a filtered subset, very strange things happen. I can't really put my finger on it but it looks like the updating clearly goes awry.
Cheers

**Comment by sarendipitee** [comment]
Not noticing anything weird myself. Can you be more specific?

**Comment by sarendipitee** [comment]
Ah I think I see what you're talking about after playing with it more. I think what is happening is that it's updating the data at the ID of the data in the filtered list which is not the ID of the data in the original list.

**Comment by sarendipitee** [comment]
That should fix it. Take a look when you get a chance.

**Comment by dagnelies** [comment]
Looks ok ;)
