### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by sarendipitee** [JonDum/ractive-datatable#3]
Need that shit.

**Comment by pembeci** [comment]
It may not be that hard to implement. Tutorials has [a generic example](http://learn.ractivejs.org/list-sections/5) which may be a good starting point.

**Comment by sarendipitee** [comment]
Yea definitely wouldn't be bad, just haven't needed yet on my app that I needed to make the datatable for. Will get around to it eventually when I'm not so swamped on other stuff. Feel free to get a start on it though.

**Comment by pembeci** [comment]
I am in the same situation. Waiting for summer to have time to work on things like this. I'll definitely have a try during summer if you haven't alredy nailed it.

**Comment by sarendipitee** [comment]
Done. Just pushed. No sexy icons or anything, but those can be easily changed via css. Try it out.
