### ISSUE TITLE
Editting on another page buggy ;)

### ISSUE THREAD

**Issue by dagnelies** [JonDum/ractive-datatable#4]
Hey ho! ;)
I'm not here to annoy you, I swear !
I noticed that if you go to the N-th page (not the first one) and edit an item, it'll instead ovewrite the corresponding one on the first page.

**Comment by sarendipitee** [comment]
Doh! I should really stop coding so late in the night. Don't know how I missed that. I'll have this fixed in a jiffy, thanks for noticing.

**Comment by sarendipitee** [comment]
Ok fixed this in 1b7fed54

And you're not being annoying at all, you're being super helpful! Thanks a bunch for noticing these!
