### ISSUE TITLE
Within a cell partial retrieve other row data?

### ISSUE THREAD

**Issue by mpowell-atomic** [JonDum/ractive-datatable#6]
Hi. Thank you for this component! I was wondering if it is possible to access other properties besides 'this' , for example, the id of the row within the cell partial:

{{#partial name}}
    <a href="/admin/app/{{id}}/edit">{{this}}</a>
{{/partial}}

Thanks!
Mark

**Comment by sarendipitee** [comment]
Yep totally. Ex: 

```
{{#partial ID}}
   {{ rows[r].item['Age'] }} <-- This would show Age in the ID column instead of the ID
{{/partial}}
```

Look at the main template to see how the rows and cols are being looped over.

You have access to `rows`, `r`, `cols` and `c` so you can technically get any cell from any other cell. `r` and `c` are the current index or the row and column respectively. So `rows[r]` is the current row which is an object with two keys `item` (the original data item) and `index` the _real_ index of the row in the data array, not the row index.

Isn't ractive awesome?

**Comment by mpowell-atomic** [comment]
awesome all around! thanks!
