### ISSUE TITLE
demo is failing

### ISSUE THREAD

**Issue by bboydflo** [JonDum/ractive-datatable#9]
click on demo link provided in the readme

**Comment by paulocoghi** [comment]
@JonDum 
The `ractive-loader` used in the project is outdated and conflicting with template version. We are using [rcu](https://github.com/ractivejs/rcu) v0.9.0 to solve this in our libraries.

**Comment by sarendipitee** [comment]
@paulocoghi It's nothing to do with `ractive-loader`, I just needed to update the build now that 0.8.3 is out. 

It's working again, thanks for pointing it out @bboydflo
